# single test suite, non-parallel build.

env:
  global:
    - CC_TEST_REPORTER_ID=1a24ea673b18f137681066ad3fec85badf586d66256e22aa5fd78818720464cb
language: node_js
node_js:
  - '10.14.1'
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - tsc
  - npm run test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
